import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CardButton from '../components/CardButton'
import axios from 'axios'

export default function Home() {

  const setWeather = async () => {
    let workerStatus = await axios.get('/api/display');
    if(workerStatus.data.errCode == 0){
      await axios.post('/api/display', {worker: "weather"});
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>
          <CardButton onClick={setWeather} icon="bx-cloud" text="weather"/>
          <CardButton icon="bx-signal-5" text="network" />
        </div>

      </main>

    </div>
  )
}
